name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci

    - run: npm test

    - name: Install dependencies
      run: npm ci

    - name: Install server dependencies
      run: npm ci
      working-directory: ./server

    - name: Start server
      run: |
        cd server
        npm start &
      working-directory: ./server

    - name: Wait for server to be ready
      run: sleep 5

    - name: Run tests
      run: 
        cd test
        npm test
      working-directory: ./server

    - name: Stop server
      run: kill $(lsof -t -i:5001)
