name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci

    - run: node server.js &

    - run: npm test

    - name: Install server dependencies
      run: |
        cd server
        npm ci
      working-directory: ./server

    - name: Start server
      run: |
        cd server
        node server.js &
      working-directory: ./server

    - name: Wait for server to be ready
      run: sleep 5

    - name: Test server
      run: |
        cd server
        npm test
      working-directory: ./server