name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies for client
      run: 
        cd client
        npm ci

    - name: Run client tests
      run: 
        cd client
        npm test

    - name: Install dependencies for server
      run: 
        cd server
        npm ci

    - name: Start server
      run: 
        cd server
        npm start &

    - name: Wait for server to be ready
      run: sleep 5

    - name: Run server tests
      run: 
        cd server
        npm test